version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    container_name: filmes_db
    environment:
      POSTGRES_USER: filmes_user
      POSTGRES_PASSWORD: filmes_pass123@
      POSTGRES_DB: filmes_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: filmes_api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_NAME: filmes_db
      DB_USER: filmes_user
      DB_PASSWORD: filmes_pass123@
      DB_HOST: db
      DB_PORT: 5432
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/filmes"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: