version: '3.8'

services:
  db:
    image: postgres:15
    container_name: filmes_db
    restart: always
    environment:
      POSTGRES_USER: filmes_user
      POSTGRES_PASSWORD: filmes_pass123
      POSTGRES_DB: filmes_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U filmes_user -d filmes_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - filmes_net

  api:
    build: .
    container_name: filmes_api
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_NAME: filmes_db
      DB_USER: filmes_user
      DB_PASSWORD: filmes_pass123
      DB_HOST: db
      DB_PORT: 5432
    networks:
      - filmes_net

volumes:
  pgdata:

networks:
  filmes_net: